apiVersion: v1
kind: Service 
metadata:
    name: webapp-k8s-service
spec:
    type: NodePort
    selector: 
      app: webapp
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30110
