apiVersion: apps/v1
kind: Deployment 
metadata:
    name: webapp
spec:
    replicas: 1
    selector: 
      matchLabels:
        app: webapp
    template:
      metadata:
        labels:
          app: webapp
      spec:
        containers:
        - name: systeminfo
          image: icnaan/systeminfo:v1.0.0
          ports: 
          - containerPort: 5000

